server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      # Configuración SSL para permitir certificados autofirmados
      httpclient:
        ssl:
          use-insecure-trust-manager: true

      routes:
           - id: customer-service
             uri: lb://customer-service
             predicates:
               - Path=/customer-service/**
             filters:
               - StripPrefix=1
           - id: invoice-service
             uri: lb://invoice-service
             predicates:
               - Path=/invoice-service/**
             filters:
               - StripPrefix=1
           - id: product-service
             uri: lb://product-service
             predicates:
               - Path=/product-service/**
             filters:
               - StripPrefix=1
           - id: servicio-autenticacion
             uri: https://localhost:8081/
             predicates:
               - Path=/servicio-autenticacion/**
             filters:
               - StripPrefix=1

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka
 instance:
   prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway